from pathlib import Path
p=Path('index.html')
t=p.read_text(encoding='utf-8')

required=[
    "const WAR_UNIT_COSTS=Object.freeze({warrior:100,brownWarrior:450,king:500,golem:550,mage:550,dragon:450,naja:550,anubis:450,isis:500});",
    "function spawnIsis(",
    "e.hp=e.maxHp=265;e.shield=e.maxShield=165;e.damage=ISIS_NORMAL_DAMAGE_1",
    "const ISIS_NORMAL_DAMAGE_1=Math.max(0,BROWN_NORMAL_DAMAGE_1-15);",
    "const ISIS_NORMAL_DAMAGE_2=Math.max(0,BROWN_NORMAL_DAMAGE_2-15);",
    "const NAJA_NORMAL_DAMAGE=65;",
    "applyCombatHit(target,e,NAJA_NORMAL_DAMAGE,{knockForce:220,knockTime:.12,tilt:9});",
    "const MAGE_NORMAL_TICK_DAMAGE=5;",
    "const EGYPT_MAGE_NORMAL_TICK_DAMAGE=MAGE_NORMAL_TICK_DAMAGE+5;",
    "const normalDamage=e.clan==='egypt'?EGYPT_MAGE_NORMAL_TICK_DAMAGE:MAGE_NORMAL_TICK_DAMAGE;",
    "const ISIS_SPECIAL_DELAY_MS=2000;",
    "const ISIS_HEAL_AMOUNT=40;",
    "const ISIS_SECOND_HEAL_AMOUNT=20;",
    "const ISIS_BLESSING_IMMUNITY_MS=1000;",
    "const ISIS_POWER_REPEAT_COUNT=2;",
    "const ISIS_SHIELD_BREAK_COOLDOWN_MS=1000;",
    "const ISIS_SELF_HEAL_AMOUNT=5;",
    "const ISIS_SHIELD_BREAK_TRIGGER_COUNT=3;",
    "const ISIS_FLIGHT_LIFT=52;",
    "const ISIS_MAX_ALLIES=2;",
    "const ISIS_HEAL_REUSE_LOCK_MS=5000;",
    "const ISIS_SPRITE_OFFSET_X=26;",
    "const ISIS_SPRITE_OFFSET_Y=-6;",
    "const ISIS_RUNTIME_REVISION='isis-double-heal-v5-20260919';",
    "function isisShieldBreakRequirement(",
    "function refreshIsisShieldSpecialTrigger(",
    "target.isisShieldBreakCount=Math.max(ISIS_SHIELD_BREAK_TRIGGER_COUNT,Number(target.isisShieldBreakCount)||0);",
    "e.isisShieldSpecialReadyAt=now+ISIS_SHIELD_BREAK_COOLDOWN_MS;",
    "if(isisBlessingProtected(target))return;",
    "if(attacker.type==='isis'&&target?.type==='dragon')return false;",
    "secondHealAt:now+powerCycleDuration",
    "fullHpImmunityGranted:false",
    "if(!blessing.secondHealDone&&now>=Number(blessing.secondHealAt||Infinity)){",
    "if(!blessing.fullHpImmunityGranted&&maxHp>0&&Number(ally.hp)>=maxHp&&now<Number(blessing.endAt||0)){",
    "ally.hp=Math.min(maxHp,beforeHp+ISIS_SECOND_HEAL_AMOUNT);",
    "function isisTeamHasNonIsisAlly(",
    "function isisAllyReservedByOther(",
    "function canIsisBlessAlly(",
    "ally.isisHealOwnerId=e.id;",
    "ally.isisHealOwnerUntil=reserveUntil;",
    "ally.isisHealBlockedUntil=now+ISIS_HEAL_REUSE_LOCK_MS;",
    "if(e.type==='isis')releaseIsisHealingReservations(e);",
    ".entity-visual.egypt-unit:not(.mage-visual):not(.isis-visual) .entity-body{",
    ".entity-visual.isis-visual .entity-body{left:-23px;top:-13px;width:142px;height:166px;object-fit:contain}",
    "const isisFacingX=(face>=0?ISIS_SPRITE_OFFSET_X:-ISIS_SPRITE_OFFSET_X);",
    "el._facing.style.left=isisFacingX+'px'",
    "el._facing.style.top=ISIS_SPRITE_OFFSET_Y+'px'",
    "const warSeparationLiving=[];",
    "const r=Math.max(0,Number(e.r)||0);",
    "e.x=clamp(e.x,WAR_ARENA_INSET.left+r,state.world.w-WAR_ARENA_INSET.right-r);",
    "function warGridKey(x,y){return (x<<16)^(y&0xffff)}",
    "const renderIsisEffectEntities=[];",
    "const sprites=el._spriteEntries||",
    "const ENTITY_LOOP_GIF_GRACE_MS=450;",
    "const warCandidateLists=new Map();",
    "if(!local){local=[];warCandidateLists.set(e.id,local)}else local.length=0;",
    "warCandidateLists.clear();",
    "translate3d(${renderX}px,${visualTop}px,0)",
    "const old=previous.get(e.id),localNow=remoteNow;",
    "e.speed=state.mode==='war'?102*WAR_TROOP_SPEED_MULTIPLIER:102;",
    "if(isisSpecialProtected(target))return;",
    "function isAirborneCombatTarget(",
    "function unitCannotHitFlying(",
    "function registerIsisAllyShieldBreak(",
    "registerIsisAllyShieldBreak(target)",
    "const normalSpecialDue=(Number(e.isisNormalCount)||0)>=4;",
    "const shieldSpecialReady=shieldArmed&&now>=Number(e.isisShieldSpecialReadyAt||0);",
    "e.hp=Math.min(Number(e.maxHp)||0,beforeSelf+ISIS_SELF_HEAL_AMOUNT);",
    "ally.hp=Math.min(maxHp,beforeHp+ISIS_HEAL_AMOUNT);",
    "const selectedAllies=selectIsisSpecialAllies(e,now,blessingEndAt);",
    "for(let i=0;i<selectedAllies.length;i++){",
    "ally.isisLastHealedAt=now;",
    "p.nextSelfHealAt+=ISIS_HEAL_TICK_MS;",
    "flightLift=ISIS_FLIGHT_LIFT",
    "e.type==='isis'?1.00",
    "img.style.width=(178*zoom)+'px'",
    "out.isisShieldBreakCount=Number(e.isisShieldBreakCount)||0;",
    "assets/egypt/isis/card.png",
    "assets/egypt/isis/walk.gif",
    "assets/egypt/isis/idle.gif",
    "assets/egypt/isis/attack-normal.gif",
    "assets/egypt/isis/special.gif",
    "assets/egypt/isis/power-special.gif",
    "function updateIsisAttackState(",
    "function syncIsisPowerEffects(",
    "const WAR_BASIC_WARRIOR_SPEED_MULTIPLIER=.92;",
    "e.attackCooldown=e.type==='king'?.65:e.type==='warrior'?.70:.50;",
    "e.damage=33;",
    "e.hp=e.maxHp=650;",
    "e.shield=e.maxShield=250;",
    "e.hp=e.maxHp=265;",
    "e.shield=e.maxShield=165;",
    "e.type==='brownWarrior'?1.16",
    "e.type==='king'?0.88",
    "e.hp=e.maxHp=165;e.shield=e.maxShield=65;e.damage=ANUBIS_PROJECTILE_DAMAGE",
    "e.hp=e.maxHp=165;e.shield=e.maxShield=65;e.damage=DRAGON_FIREBALL_DAMAGE",
    "content:attr(data-unit-name);",
    ".entity-visual:not(.dying).entity-ui-hovered .entity-bars,",
    ".entity-visual:not(.dying).entity-ui-selected .entity-bars{",
    "function entityUiDisplayName(e){",
    "function setSelectedEntityUi(entityId=null){",
    "entityBars.dataset.unitName=entityUiDisplayName(e);",
    "setSelectedEntityUi(hit.dataset.entityId);",
    "--entity-ui-inverse-scale",
    "filter:url(#entityWhiteAlphaOutline) !important;",
    "<filter id=\"entityWhiteAlphaOutline\"",
    "<feMorphology in=\"SourceAlpha\" operator=\"dilate\" radius=\"1.15\"",
    "<feComposite in=\"outlineDilated\" in2=\"SourceAlpha\" operator=\"out\"",
    "<feMergeNode in=\"whiteOutline\"/>",
    "width:80px !important;",
    "font-size:20px;",
    "-webkit-text-stroke:1px #000;",
    "el.style.setProperty('--entity-ui-inverse-scale',String(uiInverseScale));",
    "selectedEntityUiId=null;",
    "function entityUiImageAlphaHit(img,clientX,clientY){",
    "if(isPortraitFallback()){",
    "const logical=screenPointToGame(clientX,clientY);",
    "function entityUiVisiblePixelHit(el,clientX,clientY){",
    "function entityUiElementAtVisiblePixel(clientX,clientY){",
    "entityUiAlphaCtx.getImageData(0,0,1,1).data[3]>=20",
    "node.classList.toggle('entity-ui-selected'",
    "hoveredEntityUiNode?.classList.add('entity-ui-hovered')",
    "Math.hypot(ev.clientX-press.x,ev.clientY-press.y)>8",
    "el.dataset.entityId=entityId;",
    "const warCameraSurface=$('#gameScreen');",
    "warCameraSurface.addEventListener('contextmenu',e=>e.preventDefault());",
    "warCameraSurface.addEventListener('wheel',e=>{",
    "function warCameraMinZoom(){",
    "function isPortraitFallback(){",
    "const rawH=Math.max(1,innerHeight||document.documentElement.clientHeight||1);",
    "const vv=window.visualViewport;",
    "root.style.transform=`translate(-50%,-50%) rotate(90deg) scale(${scale})`;",
    "window.visualViewport?.addEventListener('resize',normalizeMobileViewport,{passive:true});",
    "window.addEventListener('pageshow',normalizeMobileViewport);",
    "return Math.max(.55,w/state.world.w,h/state.world.h);",
    "newZoom=clamp(newZoom,warCameraMinZoom(),2.15);",
    "warCameraSurface.addEventListener('pointerdown',e=>{",
    "warCameraSurface.setPointerCapture?.(e.pointerId);",
    "if(state.mode!=='war'||e.button!==2||warCameraInputBlocked(e.target))return;",
    "top:-4px !important;",
    "bottom:21px;",
    ".entity-visual .hp-bg{top:0 !important;height:8px !important}",
    ".entity-visual .shield-bg{top:12px !important;height:6px !important}",
]
missing=[x for x in required if x not in t]
if missing:
    raise SystemExit('War rebalance v3 missing: '+repr(missing))

forbidden=[
    ".entity-visual.egypt-unit:not(.mage-visual) .entity-body{",
    "const hasNonIsisAlly=teamAllies.some(ally=>ally.type!=='isis');",
    "if(reserved.has(ally.id))continue;",
    "if(isisProtected)amount=5;",
    "const ISIS_HEAL_AMOUNT=15;",
    "const ISIS_HEAL_AMOUNT=20;",
    "const ISIS_HEAL_AMOUNT=25;",
    "const ISIS_SPRITE_OFFSET_Y=2;",
    "e.type==='isis'?1.25",
    "const ISIS_RUNTIME_REVISION='isis-heal-runtime-v2-20260918';",
    "nextHealRemainingMs",
    "blessing.nextHealAt",
    "const ISIS_MAX_ALLIES=3;",
    "const ISIS_SPRITE_OFFSET_Y=24;",
    "const ISIS_SPRITE_OFFSET_Y=12;",
    "e.type==='isis'?1.44",
    "e.type==='king'?0.96",
    "const ISIS_SPRITE_OFFSET_Y=-18;",
    ".entity-visual.isis-visual .entity-body{left:-13px;top:-18px;width:142px;height:166px;object-fit:contain}",
    "e.type==='isis'?1.32",
    "const ENTITY_LOOP_GIF_GRACE_MS=1400;",
    "applyCombatHit(target,e,60,{knockForce:220,knockTime:.12,tilt:9});",
    "assets/egypt/isis/card.webp",
    "assets/egypt/isis/idle.webp",
    "assets/egypt/isis/walk.webp",
    "assets/egypt/isis/attack-normal.webp",
    "assets/egypt/isis/special.webp",
    "assets/egypt/isis/power-special.webp",
    "drop-shadow(1.35px 0 0 var(--team-outline))",
    "--entity-ui-outline-local-neg",
    "drop-shadow(var(--entity-ui-outline-local,1px) 0 0 rgba(255,255,255,.96))",
    ".entity-visual:not(.dying):hover .entity-bars,",
    "ev.stopPropagation();\n   setSelectedEntityUi(entityId);",
    "canvas.addEventListener('wheel',e=>{",
    "canvas.addEventListener('pointerdown',e=>{\n if(state.mode!=='war'||e.pointerType!=='touch')return;",
]
stale=[x for x in forbidden if x in t]
if stale:
    raise SystemExit('Old Isis assets still referenced: '+repr(stale))

print('War rebalance v3 validated.')
