"""Import a saved History editor HTML without changing editor coordinates or rules."""
import base64, hashlib, io, json, pathlib, re, sys
from PIL import Image
ROOT=pathlib.Path(__file__).resolve().parents[1]
version=sys.argv[2] if len(sys.argv)>2 else 'history-castle-v7'
asset_version=version.rsplit('-',1)[-1]
p=json.loads(re.search(r'<script id="projectData" type="application/json">(.*?)</script>',pathlib.Path(sys.argv[1]).read_text(),re.S)[1])
existing={hashlib.sha256(f.read_bytes()).hexdigest():f.relative_to(ROOT).as_posix() for f in (ROOT/'assets/history').glob('map-*/*') if f.is_file()}
assets=[];durations={};refs={}
def asset(src):
 if not src: return None
 if not src.startswith('data:'): return src
 raw=base64.b64decode(src.split(',',1)[1]);sha=hashlib.sha256(raw).hexdigest();ext={'image/webp':'webp','image/gif':'gif','image/png':'png','image/jpeg':'jpg'}[src.split(';')[0][5:]]
 url=existing.get(sha,f'assets/history/map-{asset_version}/{sha[:16]}.{ext}')
 dest=ROOT/url;dest.parent.mkdir(parents=True,exist_ok=True)
 if not dest.exists():dest.write_bytes(raw)
 try:
  im=Image.open(io.BytesIO(raw));durations[url]=sum((im.seek(i),im.info.get('duration',0))[1] for i in range(getattr(im,'n_frames',1))) or 1000
 except Exception:durations[url]=1000
 if url not in assets:assets.append(url)
 return url
for k,v in p['assets'].items():refs[k]=asset(v)
def index(ref):
 if not ref:return None
 url=refs.get(ref.get('assetId')) or asset(ref.get('src'))
 return assets.index(url) if url else None
def rect(o):
 c=o.get('collisionShape',{});r=c.get('rect',{})
 if c.get('mode')=='custom':return [o['x']+o['w']*r.get('x',0),o['y']+o['h']*r.get('y',0),o['w']*r.get('w',1),o['h']*r.get('h',1)]
 return [o[k] for k in ['x','y','w','h']]
visuals=[];colliders=[];doors=[];objects=[];bosses=[]
for o in p['objects']:
 b=o.get('boss',{});idle=next((m['asset'] for m in b.get('moves',{}).get('idle',[]) if index(m.get('asset')) is not None),None)
 ai=index(idle or {'assetId':o.get('assetId'),'src':o.get('src')}) if o['type'] in ['asset','door','boss'] else None
 oi=len(visuals) if ai is not None else None
 if ai is not None:visuals.append([ai,o['x'],o['y'],o['w'],o['h'],{'ground':0,'below':1,'dynamic':2,'above':3,'top':4}.get(o.get('depth'),1),o.get('z',200)])
 base={k:o[k] for k in ['id','x','y','w','h']};base.update(objectIndex=oi,collision=bool(o.get('collision')),collisionRect=rect(o),collisionShape=o.get('collisionShape',{}).get('shape','rect'))
 d=o.get('interaction',{}).get('destructible',{})
 if o['type']=='door':
  door={**base,**o.get('door',{})};door['openAsset']=index(door.get('openAsset'));door['transitionAsset']=index(door.get('transitionAsset'))
  door['transitionDurationMs']=durations.get(assets[door['transitionAsset']],1000) if door['transitionAsset'] is not None else 1000
  doors.append(door)
 elif o['type']=='boss':
  moves=json.loads(json.dumps(b.get('moves',{})))
  for kind,items in moves.items():
   for m in items:
    m['asset']=index(m.get('asset'))
    m['gifDurationMs']=durations.get(assets[m['asset']],1000) if m['asset'] is not None else 1000
  boss={**base,'kind':'boss','hp':b.get('hp',3000),'shield':b.get('shield',1500),'moves':moves,'pattern':b.get('pattern',[]),'respawn':False,'removeCollisionOnBreak':True,'fadeOut':True,'fadeOutSeconds':.35,'breakDurationMs':0,'xp':0}
  objects.append(boss);bosses.append(boss)
 elif d.get('enabled'):
  ob={**base,**d,'kind':'destructible','xp':o.get('interaction',{}).get('xp',{}).get('amount',0) if o.get('interaction',{}).get('xp',{}).get('enabled') else 0}
  ob['brokenAsset']=index(d.get('brokenAsset'));ob['breakDurationMs']=durations.get(assets[ob['brokenAsset']],1000) if ob['brokenAsset'] is not None and d.get('breakEndMode')=='gif_end' else max(50,d.get('breakDurationSeconds',1)*1000)
  objects.append(ob)
 elif o.get('collision'):colliders.append(rect(o))
events=json.loads(json.dumps(p['events']))
for e in events:
 if e['kind']=='enemy_spawn':e.setdefault('limitAlive',True)
 if e['kind']=='checkpoint':e['respawn']={'x':e['x'],'y':e['y']}
spawn=next(e for e in events if e['kind']=='player_start')
m={'id':version,'width':3200,'height':2200,'spawn':{'x':spawn['x'],'y':spawn['y']},'visualCount':len(visuals),'colliderCount':len(colliders),'doorCount':len(doors),'eventCount':len(events),'assets':assets,'objects':visuals,'colliders':colliders,'doors':doors,'events':events,'destructibles':objects,'bosses':bosses}
compact=lambda x:json.dumps(x,ensure_ascii=False,separators=(',',':'))
(ROOT/'assets/history/map-config.js').write_text('/* Generated by scripts/import-history-map.py from the supplied editor project. */\nwindow.RAMPAGE_HISTORY_MAP=Object.freeze('+compact(m)+');\n')
exports={'ID':m['id'],'WORLD':{'width':3200,'height':2200},'SPAWN':m['spawn'],'PLAY_BOUNDS':{'left':30,'right':3170,'top':30,'bottom':2170},'COLLIDERS':colliders,'DOORS':doors,'EVENTS':events,'OBJECTS':objects}
(ROOT/'history-server/src/map.js').write_text('/* Generated from the same editor project as assets/history/map-config.js. */\n'+''.join('export const HISTORY_MAP_'+k+' = '+(compact(v) if isinstance(v,str) else 'Object.freeze('+compact(v)+')')+';\n' for k,v in exports.items()))
# A small source manifest retains editor rules for auditing, with embedded images replaced by repository URLs.
p['assets']=refs
for o in p['objects']:
 if o.get('src','').startswith('data:'):
  o['src']=assets[visuals[next(x['objectIndex'] for x in objects if x['id']==o['id'])][0]] if o['type']=='boss' else asset(o['src'])
(ROOT/'assets/history/editor-project.json').write_text(compact(p)+'\n')
print({k:m[k] for k in ['id','visualCount','colliderCount','doorCount','eventCount']},'objects',len(objects),'assets',len(assets))
